import { title } from "motion/react-client";

const mahsulotKategoriya = [
  "Elektronika",
  "Maishiy texnika",
  "Kiyimlar",
  "Oyoq kiyimlari",
  "Aksessuarlar",
  "Go'zallik va g'amxo'rlik",
  "Salomatlik",
  "Uy-ro'zg'or buyumlari",
];

const sliderImages = [
  "https://images.uzum.uz/d0dkfd0n274j5sclnom0/main_page_banner.jpg",
  "https://images.uzum.uz/d049tutpb7f46s8834ug/main_page_banner.jpg",
  "https://images.uzum.uz/cvcg2f3vgbkm5ehkika0/main_page_banner.jpg",
  "https://images.uzum.uz/d0ddtc0n274j5scll7v0/main_page_banner.jpg",
  "https://images.uzum.uz/d07o9rdpb7f46s88qkdg/main_page_banner.jpg",
  "https://images.uzum.uz/d03ipami4n37npapm39g/main_page_banner.jpg",
  "https://images.uzum.uz/d0cp5bojsv1iusmhnu90/main_page_banner.jpg",
  "https://images.uzum.uz/d0cs05dpb7f9p3nfg2bg/main_page_banner.jpg",
  "https://images.uzum.uz/cv4o265pb7f9qcng1frg/main_page_banner.jpg",
  "https://images.uzum.uz/d03ipsdpb7f46s87tj2g/main_page_banner.jpg",
  "https://images.uzum.uz/cvqaspmi4n37npankdg0/main_page_banner.jpg",
  "https://images.uzum.uz/cvc2fjbvgbkm5ehkfu70/main_page_banner.jpg",
  "https://images.uzum.uz/d0cp33gjsv1iusmhntt0/main_page_banner.jpg",
  "https://images.uzum.uz/d03iqdk7fd1idpht5ne0/main_page_banner.jpg",
  "https://images.uzum.uz/d08dgjtpb7f46s88vir0/main_page_banner.jpg",
  "https://images.uzum.uz/d07nnrmf4hvqhbr3vr2g/main_page_banner.jpg",
  "https://images.uzum.uz/d0cr9b0jsv1iusmhoj5g/main_page_banner.jpg",
  "https://images.uzum.uz/d0ctaii7s4fo7mq81ckg/main_page_banner.jpg",
  "https://images.uzum.uz/d0e5a6on274j5sclr0g0/main_page_banner.jpg",
  "https://images.uzum.uz/d07mq6lpb7f46s88q100/main_page_banner.jpg",
  "https://images.uzum.uz/cvqbgqs7fd1p445rop40/main_page_banner.jpg",
  "https://images.uzum.uz/d0cpqcdpb7f9p3nffbdg/main_page_banner.jpg",
  "https://images.uzum.uz/d0d610r3uvph509t1g40/main_page_banner.jpg",
  "https://images.uzum.uz/d0dir633uvph509t3nn0/main_page_banner.jpg",
];

const fourtProduct = [
  {
    id: 1,
    url: "https://static.uzum.uz/static/promo_images/756b6f56-9d2d-414c-a9d3-37d40d1c808b",
    title: "Onalar va bolalar uchun",
  },
  {
    id: 2,
    url: "https://static.uzum.uz/static/promo_images/65832182-a412-4676-994d-4d0ff4083253",
    title: "Arzon narxlar kafolati",
  },
  {
    id: 3,
    url: "https://static.uzum.uz/static/promo_images/bd2c8d3a-7488-4b12-84f8-0a816bc4a359",
    title: "Zamonaviy bozor",
  },
  {
    id: 4,
    url: "https://static.uzum.uz/static/promo_images/a98e3eef-162f-47b1-b8d8-f6253393bd95",
    title: "Hafta tovarlari",
  },
];

const productCard = [
  {
    id: 1,
    title:
      "Atir Hayati erkakalar uchun parfumlangan suv Lattafa Hayayti, mamuna, 100 ml",
    price: "17 900",
    monthlyPrice: "1 267 so'm/oyiga",
    rating: "4.8 (122 sharhlar)",
    label: ["Katta savdo"],
    reviewLabel: "Arzon narx kafolati",
    image: "https://images.uzum.uz/culcgemi4n324lr9el5g/t_product_540_high.jpg",
  },

  {
    id: 2,
    title: "Simsiz quloqchinlar Pro/Naushnik/airpods",
    price: "30 000",
    monthlyPrice: "2 125 so'm/oyiga",
    rating: "4.3 (575 sharhlar)",
    label: ["Katta savdo"],
    reviewLabel: "Arzon narx kafolati",
    image: "https://images.uzum.uz/cu5p4245j42bjc48vt30/t_product_540_high.jpg",
  },

  {
    id: 3,
    title: "Gaz plita Ideal L115, 4 konforka, pech hajmi 65 litr, 60 * 60 sm",
    price: "2 299 000",
    monthlyPrice: "162 845 so'm/oyiga",
    rating: "4.9 (51 sharhlar)",
    label: ["Katta savdo"],
    reviewLabel: "Arzon narx kafolati",
    image: "https://images.uzum.uz/cu0v1k5ht56ksubcpk4g/t_product_540_high.jpg",
  },

  {
    id: 4,
    title: "Kompyuter uchun ko'zoynak-antibka",
    price: "21 900",
    monthlyPrice: "1 551 so'm/oyiga",
    rating: "4.9 (137 sharhlar)",
    label: ["Katta savdo"],
    reviewLabel: "Arzon narx kafolati",
    image: "https://images.uzum.uz/cuqus5tpb7f8r31vn43g/t_product_540_high.jpg",
  },

  {
    id: 5,
    title: "Smartfon Infinix Hot 50i, 6+6/128GB",
    price: "1 299 000",
    monthlyPrice: "92 012 so'm/oyiga",
    rating: "5.0 (1 sharhlar)",
    label: ["Katta savdo"],
    reviewLabel: "Arzon narx kafolati",
    image: "https://images.uzum.uz/d0bntpt4b5n4best09p0/t_product_540_high.jpg",
  },

  {
    id: 6,
    title: "Smartfon Redmi note 14, 8GB+256GB, AMOLED 120Hz displey, 6.67",
    price: "1 999 000",
    monthlyPrice: "141 595 so'm/oyiga",
    rating: "4.9 (17 sharhlar)",
    label: ["Super narx"],
    reviewLabel: "Arzon narx kafolati",
    image: "https://images.uzum.uz/cu8eg36i4n324lr5k190/t_product_540_high.jpg",
  },

  {
    id: 7,
    title:
      "Soch va soqol uchun trimmmer erkaklar uchun professional, 4 nasadka",
    price: "32 000",
    monthlyPrice: "2 266 so'm/oyiga",
    rating: "4.9 (676 sharhlar)",
    label: ["Katta savdo"],
    reviewLabel: "Arzon narx kafolati",
    image: "https://images.uzum.uz/cvrv4j47fd1p445s6jrg/t_product_540_high.jpg",
  },

  {
    id: 8,
    title: "Xurmo KALOOTEH, 500 g",
    price: "17 990",
    monthlyPrice: "1 274 so'm/oyiga",
    rating: "4.9 (2248 sharhlar)",
    label: ["Katta savdo"],
    reviewLabel: "Arzon narx kafolati",
    image: "https://images.uzum.uz/cunc2rmi4n324lra3ctg/t_product_540_high.jpg",
  },

  {
    id: 9,
    title: "Oshxona dudbo'roni Vesta PR-860",
    price: "699 000",
    monthlyPrice: "49 512 so'm/oyiga",
    rating: "4.8 (22 sharhlar)",
    label: ["Katta savdo"],
    reviewLabel: "Arzon narx kafolati",
    image: "https://images.uzum.uz/cv01purvgbkm5ehh5dd0/t_product_540_high.jpg",
  },

  {
    id: 10,
    title: "Bahor va yozga mo'ljallangan yengil erkaklar to'rli sliponlari",
    price: "139 000",
    monthlyPrice: "9 845 so'm/oyiga",
    rating: "4.9 (9 sharhlar)",
    label: ["Super narx"],
    reviewLabel: "Arzon narx kafolati",
    image: "https://images.uzum.uz/d0e7ltq7s4fo7mq8bbb0/t_product_540_high.jpg",
  },

  {
    id: 11,
    title: "Kvarts mexanizm soat",
    price: 773730,
    monthlyPrice: "55266 so'm/oyiga",
    rating: 4.9,
    reviewCount: 659,
    label: "",
    category: "Soatlar",
    image: "https://example.com/images/product11.jpg",
  },
  // {
  //   id: 12,
  //   title: "Kvarts mexanizm soat",
  //   price: 994587,
  //   monthlyPrice: "71041 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 663,
  //   label: "Katta savdo",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product12.jpg",
  // },
  // {
  //   id: 13,
  //   title: "Sport soat",
  //   price: 906993,
  //   monthlyPrice: "64785 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 758,
  //   label: "Chegirma",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product13.jpg",
  // },
  // {
  //   id: 14,
  //   title: "Sport soat",
  //   price: 659624,
  //   monthlyPrice: "47116 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 144,
  //   label: "Katta savdo",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product14.jpg",
  // },
  // {
  //   id: 15,
  //   title: "Sport soat",
  //   price: 354085,
  //   monthlyPrice: "25291 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 1000,
  //   label: "Katta savdo",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product15.jpg",
  // },
  // {
  //   id: 16,
  //   title: "Sport soat",
  //   price: 896296,
  //   monthlyPrice: "64021 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 618,
  //   label: "",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product16.jpg",
  // },
  // {
  //   id: 17,
  //   title: "Sport soat",
  //   price: 877053,
  //   monthlyPrice: "62646 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 51,
  //   label: "Chegirma",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product17.jpg",
  // },
  // {
  //   id: 18,
  //   title: "Sport soat",
  //   price: 995020,
  //   monthlyPrice: "71072 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 611,
  //   label: "Super narx",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product18.jpg",
  // },
  // {
  //   id: 19,
  //   title: "Sport soat",
  //   price: 603037,
  //   monthlyPrice: "43074 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 227,
  //   label: "Katta savdo",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product19.jpg",
  // },
  // {
  //   id: 20,
  //   title: "Sport soat",
  //   price: 328156,
  //   monthlyPrice: "23439 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 893,
  //   label: "Chegirma",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product20.jpg",
  // },
  // {
  //   id: 21,
  //   title: "Sport soat",
  //   price: 113925,
  //   monthlyPrice: "8137 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 489,
  //   label: "Yangi",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product21.jpg",
  // },
  // {
  //   id: 22,
  //   title: "Sport soat",
  //   price: 231875,
  //   monthlyPrice: "16562 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 710,
  //   label: "Yangi",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product22.jpg",
  // },
  // {
  //   id: 23,
  //   title: "Sport soat",
  //   price: 768659,
  //   monthlyPrice: "54904 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 899,
  //   label: "Katta savdo",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product23.jpg",
  // },
  // {
  //   id: 24,
  //   title: "Sport soat",
  //   price: 172385,
  //   monthlyPrice: "12313 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 689,
  //   label: "",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product24.jpg",
  // },
  // {
  //   id: 25,
  //   title: "Minimalist soat",
  //   price: 756408,
  //   monthlyPrice: "54029 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 978,
  //   label: "",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product25.jpg",
  // },
  // {
  //   id: 26,
  //   title: "Minimalist soat",
  //   price: 81611,
  //   monthlyPrice: "5829 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 344,
  //   label: "",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product26.jpg",
  // },
  // {
  //   id: 27,
  //   title: "Minimalist soat",
  //   price: 799772,
  //   monthlyPrice: "57126 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 424,
  //   label: "",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product27.jpg",
  // },
  // {
  //   id: 28,
  //   title: "Minimalist soat",
  //   price: 858525,
  //   monthlyPrice: "61323 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 192,
  //   label: "Super narx",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product28.jpg",
  // },
  // {
  //   id: 29,
  //   title: "Minimalist soat",
  //   price: 528308,
  //   monthlyPrice: "37736 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 488,
  //   label: "",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product29.jpg",
  // },
  // {
  //   id: 30,
  //   title: "Minimalist soat",
  //   price: 225644,
  //   monthlyPrice: "16117 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 78,
  //   label: "",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product30.jpg",
  // },
  // {
  //   id: 31,
  //   title: "Minimalist soat",
  //   price: 188676,
  //   monthlyPrice: "13476 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 581,
  //   label: "",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product31.jpg",
  // },
  // {
  //   id: 32,
  //   title: "Minimalist soat",
  //   price: 934883,
  //   monthlyPrice: "66777 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 967,
  //   label: "Super narx",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product32.jpg",
  // },
  // {
  //   id: 33,
  //   title: "Minimalist soat",
  //   price: 635810,
  //   monthlyPrice: "45415 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 975,
  //   label: "",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product33.jpg",
  // },
  // {
  //   id: 34,
  //   title: "Minimalist soat",
  //   price: 948923,
  //   monthlyPrice: "67780 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 463,
  //   label: "Chegirma",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product34.jpg",
  // },
  // {
  //   id: 35,
  //   title: "Minimalist soat",
  //   price: 903917,
  //   monthlyPrice: "64565 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 200,
  //   label: "Yangi",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product35.jpg",
  // },
  // {
  //   id: 36,
  //   title: "Minimalist soat",
  //   price: 288530,
  //   monthlyPrice: "20609 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 503,
  //   label: "Chegirma",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product36.jpg",
  // },
  // {
  //   id: 37,
  //   title: "Metall korpus soat",
  //   price: 172797,
  //   monthlyPrice: "12342 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 162,
  //   label: "Super narx",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product37.jpg",
  // },
  // {
  //   id: 38,
  //   title: "Metall korpus soat",
  //   price: 999368,
  //   monthlyPrice: "71383 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 176,
  //   label: "Chegirma",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product38.jpg",
  // },
  // {
  //   id: 39,
  //   title: "Metall korpus soat",
  //   price: 235051,
  //   monthlyPrice: "16789 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 487,
  //   label: "Super narx",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product39.jpg",
  // },
  // {
  //   id: 40,
  //   title: "Metall korpus soat",
  //   price: 891568,
  //   monthlyPrice: "63683 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 227,
  //   label: "Yangi",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product40.jpg",
  // },
  // {
  //   id: 41,
  //   title: "Metall korpus soat",
  //   price: 127525,
  //   monthlyPrice: "9108 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 971,
  //   label: "",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product41.jpg",
  // },
  // {
  //   id: 42,
  //   title: "Metall korpus soat",
  //   price: 534469,
  //   monthlyPrice: "38176 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 197,
  //   label: "Katta savdo",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product42.jpg",
  // },
  // {
  //   id: 43,
  //   title: "Metall korpus soat",
  //   price: 284871,
  //   monthlyPrice: "20347 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 112,
  //   label: "Yangi",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product43.jpg",
  // },
  // {
  //   id: 44,
  //   title: "Metall korpus soat",
  //   price: 731064,
  //   monthlyPrice: "52218 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 829,
  //   label: "",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product44.jpg",
  // },
  // {
  //   id: 45,
  //   title: "Metall korpus soat",
  //   price: 729793,
  //   monthlyPrice: "52128 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 501,
  //   label: "Yangi",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product45.jpg",
  // },
  // {
  //   id: 46,
  //   title: "Metall korpus soat",
  //   price: 667678,
  //   monthlyPrice: "47691 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 621,
  //   label: "Yangi",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product46.jpg",
  // },
  // {
  //   id: 47,
  //   title: "Metall korpus soat",
  //   price: 387497,
  //   monthlyPrice: "27678 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 776,
  //   label: "Super narx",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product47.jpg",
  // },
  // {
  //   id: 48,
  //   title: "Metall korpus soat",
  //   price: 584971,
  //   monthlyPrice: "41783 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 437,
  //   label: "Yangi",
  //   category: "Soatlar",
  //   image: "https://example.com/images/product48.jpg",
  // },
  // {
  //   id: 49,
  //   title: "Beysbolka Colorado",
  //   price: 673397,
  //   monthlyPrice: "48099 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 309,
  //   label: "Chegirma",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product49.jpg",
  // },
  // {
  //   id: 50,
  //   title: "Beysbolka Colorado",
  //   price: 541745,
  //   monthlyPrice: "38696 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 386,
  //   label: "Super narx",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product50.jpg",
  // },
  // {
  //   id: 51,
  //   title: "Beysbolka Colorado",
  //   price: 618228,
  //   monthlyPrice: "44159 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 468,
  //   label: "",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product51.jpg",
  // },
  // {
  //   id: 52,
  //   title: "Beysbolka Colorado",
  //   price: 269968,
  //   monthlyPrice: "19283 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 144,
  //   label: "",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product52.jpg",
  // },
  // {
  //   id: 53,
  //   title: "Beysbolka Colorado",
  //   price: 388286,
  //   monthlyPrice: "27734 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 552,
  //   label: "Super narx",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product53.jpg",
  // },
  // {
  //   id: 54,
  //   title: "Beysbolka Colorado",
  //   price: 231363,
  //   monthlyPrice: "16525 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 441,
  //   label: "Super narx",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product54.jpg",
  // },
  // {
  //   id: 55,
  //   title: "Beysbolka Colorado",
  //   price: 603822,
  //   monthlyPrice: "43130 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 929,
  //   label: "Super narx",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product55.jpg",
  // },
  // {
  //   id: 56,
  //   title: "Beysbolka Colorado",
  //   price: 443537,
  //   monthlyPrice: "31681 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 861,
  //   label: "Chegirma",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product56.jpg",
  // },
  // {
  //   id: 57,
  //   title: "Beysbolka Colorado",
  //   price: 959258,
  //   monthlyPrice: "68518 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 758,
  //   label: "Yangi",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product57.jpg",
  // },
  // {
  //   id: 58,
  //   title: "Beysbolka Colorado",
  //   price: 435594,
  //   monthlyPrice: "31113 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 965,
  //   label: "Super narx",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product58.jpg",
  // },
  // {
  //   id: 59,
  //   title: "Beysbolka Colorado",
  //   price: 391032,
  //   monthlyPrice: "27930 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 475,
  //   label: "Katta savdo",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product59.jpg",
  // },
  // {
  //   id: 60,
  //   title: "Beysbolka Colorado",
  //   price: 434717,
  //   monthlyPrice: "31051 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 815,
  //   label: "Yangi",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product60.jpg",
  // },
  // {
  //   id: 61,
  //   title: "Nike Classic kepka",
  //   price: 141241,
  //   monthlyPrice: "10088 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 316,
  //   label: "Yangi",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product61.jpg",
  // },
  // {
  //   id: 62,
  //   title: "Nike Classic kepka",
  //   price: 106315,
  //   monthlyPrice: "7593 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 760,
  //   label: "Yangi",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product62.jpg",
  // },
  // {
  //   id: 63,
  //   title: "Nike Classic kepka",
  //   price: 117779,
  //   monthlyPrice: "8412 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 571,
  //   label: "Katta savdo",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product63.jpg",
  // },
  // {
  //   id: 64,
  //   title: "Nike Classic kepka",
  //   price: 886062,
  //   monthlyPrice: "63290 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 304,
  //   label: "Super narx",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product64.jpg",
  // },
  // {
  //   id: 65,
  //   title: "Nike Classic kepka",
  //   price: 896429,
  //   monthlyPrice: "64030 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 493,
  //   label: "Katta savdo",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product65.jpg",
  // },
  // {
  //   id: 66,
  //   title: "Nike Classic kepka",
  //   price: 371018,
  //   monthlyPrice: "26501 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 949,
  //   label: "Chegirma",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product66.jpg",
  // },
  // {
  //   id: 67,
  //   title: "Nike Classic kepka",
  //   price: 845704,
  //   monthlyPrice: "60407 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 430,
  //   label: "",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product67.jpg",
  // },
  // {
  //   id: 68,
  //   title: "Nike Classic kepka",
  //   price: 839225,
  //   monthlyPrice: "59944 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 434,
  //   label: "Super narx",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product68.jpg",
  // },
  // {
  //   id: 69,
  //   title: "Nike Classic kepka",
  //   price: 564690,
  //   monthlyPrice: "40335 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 118,
  //   label: "Yangi",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product69.jpg",
  // },
  // {
  //   id: 70,
  //   title: "Nike Classic kepka",
  //   price: 188098,
  //   monthlyPrice: "13435 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 755,
  //   label: "Super narx",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product70.jpg",
  // },
  // {
  //   id: 71,
  //   title: "Nike Classic kepka",
  //   price: 162808,
  //   monthlyPrice: "11629 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 547,
  //   label: "Katta savdo",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product71.jpg",
  // },
  // {
  //   id: 72,
  //   title: "Nike Classic kepka",
  //   price: 156580,
  //   monthlyPrice: "11184 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 918,
  //   label: "",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product72.jpg",
  // },
  // {
  //   id: 73,
  //   title: "Adidas kepka",
  //   price: 363238,
  //   monthlyPrice: "25945 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 228,
  //   label: "Chegirma",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product73.jpg",
  // },
  // {
  //   id: 74,
  //   title: "Adidas kepka",
  //   price: 189951,
  //   monthlyPrice: "13567 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 349,
  //   label: "Chegirma",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product74.jpg",
  // },
  // {
  //   id: 75,
  //   title: "Adidas kepka",
  //   price: 240895,
  //   monthlyPrice: "17206 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 253,
  //   label: "Yangi",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product75.jpg",
  // },
  // {
  //   id: 76,
  //   title: "Adidas kepka",
  //   price: 679474,
  //   monthlyPrice: "48533 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 615,
  //   label: "Chegirma",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product76.jpg",
  // },
  // {
  //   id: 77,
  //   title: "Adidas kepka",
  //   price: 753355,
  //   monthlyPrice: "53811 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 979,
  //   label: "Yangi",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product77.jpg",
  // },
  // {
  //   id: 78,
  //   title: "Adidas kepka",
  //   price: 576131,
  //   monthlyPrice: "41152 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 238,
  //   label: "Super narx",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product78.jpg",
  // },
  // {
  //   id: 79,
  //   title: "Adidas kepka",
  //   price: 370300,
  //   monthlyPrice: "26450 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 272,
  //   label: "Super narx",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product79.jpg",
  // },
  // {
  //   id: 80,
  //   title: "Adidas kepka",
  //   price: 701322,
  //   monthlyPrice: "50094 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 719,
  //   label: "Super narx",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product80.jpg",
  // },
  // {
  //   id: 81,
  //   title: "Adidas kepka",
  //   price: 956391,
  //   monthlyPrice: "68313 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 879,
  //   label: "Super narx",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product81.jpg",
  // },
  // {
  //   id: 82,
  //   title: "Adidas kepka",
  //   price: 774098,
  //   monthlyPrice: "55292 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 874,
  //   label: "",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product82.jpg",
  // },
  // {
  //   id: 83,
  //   title: "Adidas kepka",
  //   price: 453653,
  //   monthlyPrice: "32403 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 140,
  //   label: "Chegirma",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product83.jpg",
  // },
  // {
  //   id: 84,
  //   title: "Adidas kepka",
  //   price: 193586,
  //   monthlyPrice: "13827 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 137,
  //   label: "Katta savdo",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product84.jpg",
  // },
  // {
  //   id: 85,
  //   title: "Denim uslubidagi kepka",
  //   price: 683378,
  //   monthlyPrice: "48812 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 854,
  //   label: "Yangi",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product85.jpg",
  // },
  // {
  //   id: 86,
  //   title: "Denim uslubidagi kepka",
  //   price: 982198,
  //   monthlyPrice: "70157 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 863,
  //   label: "",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product86.jpg",
  // },
  // {
  //   id: 87,
  //   title: "Denim uslubidagi kepka",
  //   price: 794530,
  //   monthlyPrice: "56752 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 919,
  //   label: "Katta savdo",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product87.jpg",
  // },
  // {
  //   id: 88,
  //   title: "Denim uslubidagi kepka",
  //   price: 288199,
  //   monthlyPrice: "20585 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 268,
  //   label: "Super narx",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product88.jpg",
  // },
  // {
  //   id: 89,
  //   title: "Denim uslubidagi kepka",
  //   price: 901775,
  //   monthlyPrice: "64412 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 339,
  //   label: "Katta savdo",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product89.jpg",
  // },
  // {
  //   id: 90,
  //   title: "Denim uslubidagi kepka",
  //   price: 389718,
  //   monthlyPrice: "27837 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 149,
  //   label: "",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product90.jpg",
  // },
  // {
  //   id: 91,
  //   title: "Denim uslubidagi kepka",
  //   price: 669133,
  //   monthlyPrice: "47795 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 336,
  //   label: "Katta savdo",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product91.jpg",
  // },
  // {
  //   id: 92,
  //   title: "Denim uslubidagi kepka",
  //   price: 544176,
  //   monthlyPrice: "38869 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 513,
  //   label: "Chegirma",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product92.jpg",
  // },
  // {
  //   id: 93,
  //   title: "Denim uslubidagi kepka",
  //   price: 185864,
  //   monthlyPrice: "13276 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 317,
  //   label: "Yangi",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product93.jpg",
  // },
  // {
  //   id: 94,
  //   title: "Denim uslubidagi kepka",
  //   price: 211455,
  //   monthlyPrice: "15103 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 971,
  //   label: "Chegirma",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product94.jpg",
  // },
  // {
  //   id: 95,
  //   title: "Denim uslubidagi kepka",
  //   price: 173895,
  //   monthlyPrice: "12421 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 403,
  //   label: "",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product95.jpg",
  // },
  // {
  //   id: 96,
  //   title: "Denim uslubidagi kepka",
  //   price: 84058,
  //   monthlyPrice: "6004 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 537,
  //   label: "Yangi",
  //   category: "Kepkalar",
  //   image: "https://example.com/images/product96.jpg",
  // },
  // {
  //   id: 97,
  //   title: "Yozgi ayollar ko'zoynaklari",
  //   price: 200256,
  //   monthlyPrice: "14304 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 770,
  //   label: "",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product97.jpg",
  // },
  // {
  //   id: 98,
  //   title: "Yozgi ayollar ko'zoynaklari",
  //   price: 276431,
  //   monthlyPrice: "19745 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 303,
  //   label: "Super narx",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product98.jpg",
  // },
  // {
  //   id: 99,
  //   title: "Yozgi ayollar ko'zoynaklari",
  //   price: 824603,
  //   monthlyPrice: "58900 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 243,
  //   label: "Super narx",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product99.jpg",
  // },
  // {
  //   id: 100,
  //   title: "Yozgi ayollar ko'zoynaklari",
  //   price: 378678,
  //   monthlyPrice: "27048 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 531,
  //   label: "",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product100.jpg",
  // },
  // {
  //   id: 101,
  //   title: "Yozgi ayollar ko'zoynaklari",
  //   price: 738795,
  //   monthlyPrice: "52771 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 59,
  //   label: "Yangi",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product101.jpg",
  // },
  // {
  //   id: 102,
  //   title: "Yozgi ayollar ko'zoynaklari",
  //   price: 604092,
  //   monthlyPrice: "43149 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 352,
  //   label: "Yangi",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product102.jpg",
  // },
  // {
  //   id: 103,
  //   title: "Yozgi ayollar ko'zoynaklari",
  //   price: 306567,
  //   monthlyPrice: "21897 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 653,
  //   label: "Katta savdo",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product103.jpg",
  // },
  // {
  //   id: 104,
  //   title: "Yozgi ayollar ko'zoynaklari",
  //   price: 870590,
  //   monthlyPrice: "62185 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 762,
  //   label: "Yangi",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product104.jpg",
  // },
  // {
  //   id: 105,
  //   title: "Yozgi ayollar ko'zoynaklari",
  //   price: 364184,
  //   monthlyPrice: "26013 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 906,
  //   label: "Yangi",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product105.jpg",
  // },
  // {
  //   id: 106,
  //   title: "Yozgi ayollar ko'zoynaklari",
  //   price: 378499,
  //   monthlyPrice: "27035 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 158,
  //   label: "Yangi",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product106.jpg",
  // },
  // {
  //   id: 107,
  //   title: "Yozgi ayollar ko'zoynaklari",
  //   price: 720875,
  //   monthlyPrice: "51491 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 871,
  //   label: "Super narx",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product107.jpg",
  // },
  // {
  //   id: 108,
  //   title: "Yozgi ayollar ko'zoynaklari",
  //   price: 609482,
  //   monthlyPrice: "43534 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 652,
  //   label: "Yangi",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product108.jpg",
  // },
  // {
  //   id: 109,
  //   title: "Erkaklar retro ko'zoynaklari",
  //   price: 647314,
  //   monthlyPrice: "46236 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 925,
  //   label: "Katta savdo",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product109.jpg",
  // },
  // {
  //   id: 110,
  //   title: "Erkaklar retro ko'zoynaklari",
  //   price: 937806,
  //   monthlyPrice: "66986 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 121,
  //   label: "Super narx",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product110.jpg",
  // },
  // {
  //   id: 111,
  //   title: "Erkaklar retro ko'zoynaklari",
  //   price: 440477,
  //   monthlyPrice: "31462 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 909,
  //   label: "Katta savdo",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product111.jpg",
  // },
  // {
  //   id: 112,
  //   title: "Erkaklar retro ko'zoynaklari",
  //   price: 389048,
  //   monthlyPrice: "27789 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 276,
  //   label: "Chegirma",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product112.jpg",
  // },
  // {
  //   id: 113,
  //   title: "Erkaklar retro ko'zoynaklari",
  //   price: 771703,
  //   monthlyPrice: "55121 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 799,
  //   label: "Yangi",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product113.jpg",
  // },
  // {
  //   id: 114,
  //   title: "Erkaklar retro ko'zoynaklari",
  //   price: 728719,
  //   monthlyPrice: "52051 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 893,
  //   label: "Katta savdo",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product114.jpg",
  // },
  // {
  //   id: 115,
  //   title: "Erkaklar retro ko'zoynaklari",
  //   price: 368419,
  //   monthlyPrice: "26315 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 945,
  //   label: "Yangi",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product115.jpg",
  // },
  // {
  //   id: 116,
  //   title: "Erkaklar retro ko'zoynaklari",
  //   price: 861369,
  //   monthlyPrice: "61526 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 137,
  //   label: "Katta savdo",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product116.jpg",
  // },
  // {
  //   id: 117,
  //   title: "Erkaklar retro ko'zoynaklari",
  //   price: 498750,
  //   monthlyPrice: "35625 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 201,
  //   label: "Katta savdo",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product117.jpg",
  // },
  // {
  //   id: 118,
  //   title: "Erkaklar retro ko'zoynaklari",
  //   price: 148529,
  //   monthlyPrice: "10609 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 844,
  //   label: "Katta savdo",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product118.jpg",
  // },
  // {
  //   id: 119,
  //   title: "Erkaklar retro ko'zoynaklari",
  //   price: 898186,
  //   monthlyPrice: "64156 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 420,
  //   label: "Chegirma",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product119.jpg",
  // },
  // {
  //   id: 120,
  //   title: "Erkaklar retro ko'zoynaklari",
  //   price: 579195,
  //   monthlyPrice: "41371 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 207,
  //   label: "",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product120.jpg",
  // },
  // {
  //   id: 121,
  //   title: "UV saqlovchi sport ko'zoynaklari",
  //   price: 888288,
  //   monthlyPrice: "63449 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 432,
  //   label: "Yangi",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product121.jpg",
  // },
  // {
  //   id: 122,
  //   title: "UV saqlovchi sport ko'zoynaklari",
  //   price: 86965,
  //   monthlyPrice: "6211 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 422,
  //   label: "Katta savdo",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product122.jpg",
  // },
  // {
  //   id: 123,
  //   title: "UV saqlovchi sport ko'zoynaklari",
  //   price: 776021,
  //   monthlyPrice: "55430 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 578,
  //   label: "Katta savdo",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product123.jpg",
  // },
  // {
  //   id: 124,
  //   title: "UV saqlovchi sport ko'zoynaklari",
  //   price: 187152,
  //   monthlyPrice: "13368 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 236,
  //   label: "Super narx",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product124.jpg",
  // },
  // {
  //   id: 125,
  //   title: "UV saqlovchi sport ko'zoynaklari",
  //   price: 560088,
  //   monthlyPrice: "40006 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 227,
  //   label: "Yangi",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product125.jpg",
  // },
  // {
  //   id: 126,
  //   title: "UV saqlovchi sport ko'zoynaklari",
  //   price: 466621,
  //   monthlyPrice: "33330 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 575,
  //   label: "Super narx",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product126.jpg",
  // },
  // {
  //   id: 127,
  //   title: "UV saqlovchi sport ko'zoynaklari",
  //   price: 415399,
  //   monthlyPrice: "29671 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 342,
  //   label: "Super narx",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product127.jpg",
  // },
  // {
  //   id: 128,
  //   title: "UV saqlovchi sport ko'zoynaklari",
  //   price: 412419,
  //   monthlyPrice: "29458 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 391,
  //   label: "",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product128.jpg",
  // },
  // {
  //   id: 129,
  //   title: "UV saqlovchi sport ko'zoynaklari",
  //   price: 705459,
  //   monthlyPrice: "50389 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 220,
  //   label: "Super narx",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product129.jpg",
  // },
  // {
  //   id: 130,
  //   title: "UV saqlovchi sport ko'zoynaklari",
  //   price: 768093,
  //   monthlyPrice: "54863 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 740,
  //   label: "Chegirma",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product130.jpg",
  // },
  // {
  //   id: 131,
  //   title: "UV saqlovchi sport ko'zoynaklari",
  //   price: 577508,
  //   monthlyPrice: "41250 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 128,
  //   label: "Yangi",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product131.jpg",
  // },
  // {
  //   id: 132,
  //   title: "UV saqlovchi sport ko'zoynaklari",
  //   price: 349904,
  //   monthlyPrice: "24993 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 378,
  //   label: "Yangi",
  //   category: "Ko'zoynaklar",
  //   image: "https://example.com/images/product132.jpg",
  // },
  // {
  //   id: 133,
  //   title: "Ayollar bel kamari",
  //   price: 551510,
  //   monthlyPrice: "39393 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 624,
  //   label: "Chegirma",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product133.jpg",
  // },
  // {
  //   id: 134,
  //   title: "Ayollar bel kamari",
  //   price: 934495,
  //   monthlyPrice: "66749 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 511,
  //   label: "Chegirma",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product134.jpg",
  // },
  // {
  //   id: 135,
  //   title: "Ayollar bel kamari",
  //   price: 200245,
  //   monthlyPrice: "14303 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 722,
  //   label: "Super narx",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product135.jpg",
  // },
  // {
  //   id: 136,
  //   title: "Ayollar bel kamari",
  //   price: 327573,
  //   monthlyPrice: "23398 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 732,
  //   label: "Katta savdo",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product136.jpg",
  // },
  // {
  //   id: 137,
  //   title: "Ayollar bel kamari",
  //   price: 990927,
  //   monthlyPrice: "70780 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 545,
  //   label: "Katta savdo",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product137.jpg",
  // },
  // {
  //   id: 138,
  //   title: "Ayollar bel kamari",
  //   price: 861738,
  //   monthlyPrice: "61552 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 755,
  //   label: "Yangi",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product138.jpg",
  // },
  // {
  //   id: 139,
  //   title: "Ayollar bel kamari",
  //   price: 460014,
  //   monthlyPrice: "32858 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 317,
  //   label: "",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product139.jpg",
  // },
  // {
  //   id: 140,
  //   title: "Ayollar bel kamari",
  //   price: 380855,
  //   monthlyPrice: "27203 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 874,
  //   label: "Chegirma",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product140.jpg",
  // },
  // {
  //   id: 141,
  //   title: "Ayollar bel kamari",
  //   price: 756522,
  //   monthlyPrice: "54037 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 359,
  //   label: "Yangi",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product141.jpg",
  // },
  // {
  //   id: 142,
  //   title: "Ayollar bel kamari",
  //   price: 97753,
  //   monthlyPrice: "6982 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 665,
  //   label: "Yangi",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product142.jpg",
  // },
  // {
  //   id: 143,
  //   title: "Ayollar bel kamari",
  //   price: 980565,
  //   monthlyPrice: "70040 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 201,
  //   label: "Super narx",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product143.jpg",
  // },
  // {
  //   id: 144,
  //   title: "Ayollar bel kamari",
  //   price: 650674,
  //   monthlyPrice: "46476 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 642,
  //   label: "Yangi",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product144.jpg",
  // },
  // {
  //   id: 145,
  //   title: "Erkaklar teri kamari",
  //   price: 304845,
  //   monthlyPrice: "21774 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 240,
  //   label: "Katta savdo",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product145.jpg",
  // },
  // {
  //   id: 146,
  //   title: "Erkaklar teri kamari",
  //   price: 100291,
  //   monthlyPrice: "7163 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 1000,
  //   label: "Yangi",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product146.jpg",
  // },
  // {
  //   id: 147,
  //   title: "Erkaklar teri kamari",
  //   price: 683143,
  //   monthlyPrice: "48795 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 539,
  //   label: "Chegirma",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product147.jpg",
  // },
  // {
  //   id: 148,
  //   title: "Erkaklar teri kamari",
  //   price: 446421,
  //   monthlyPrice: "31887 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 446,
  //   label: "Yangi",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product148.jpg",
  // },
  // {
  //   id: 149,
  //   title: "Erkaklar teri kamari",
  //   price: 386140,
  //   monthlyPrice: "27581 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 328,
  //   label: "Yangi",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product149.jpg",
  // },
  // {
  //   id: 150,
  //   title: "Erkaklar teri kamari",
  //   price: 898829,
  //   monthlyPrice: "64202 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 390,
  //   label: "Chegirma",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product150.jpg",
  // },
  // {
  //   id: 151,
  //   title: "Erkaklar teri kamari",
  //   price: 271695,
  //   monthlyPrice: "19406 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 850,
  //   label: "Katta savdo",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product151.jpg",
  // },
  // {
  //   id: 152,
  //   title: "Erkaklar teri kamari",
  //   price: 351990,
  //   monthlyPrice: "25142 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 283,
  //   label: "Super narx",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product152.jpg",
  // },
  // {
  //   id: 153,
  //   title: "Erkaklar teri kamari",
  //   price: 752481,
  //   monthlyPrice: "53748 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 614,
  //   label: "Chegirma",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product153.jpg",
  // },
  // {
  //   id: 154,
  //   title: "Erkaklar teri kamari",
  //   price: 281208,
  //   monthlyPrice: "20086 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 175,
  //   label: "Super narx",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product154.jpg",
  // },
  // {
  //   id: 155,
  //   title: "Erkaklar teri kamari",
  //   price: 520427,
  //   monthlyPrice: "37173 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 662,
  //   label: "",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product155.jpg",
  // },
  // {
  //   id: 156,
  //   title: "Erkaklar teri kamari",
  //   price: 793273,
  //   monthlyPrice: "56662 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 321,
  //   label: "Chegirma",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product156.jpg",
  // },
  // {
  //   id: 157,
  //   title: "Hermes uslubidagi kamar",
  //   price: 875902,
  //   monthlyPrice: "62564 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 512,
  //   label: "Yangi",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product157.jpg",
  // },
  // {
  //   id: 158,
  //   title: "Hermes uslubidagi kamar",
  //   price: 171061,
  //   monthlyPrice: "12218 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 760,
  //   label: "Super narx",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product158.jpg",
  // },
  // {
  //   id: 159,
  //   title: "Hermes uslubidagi kamar",
  //   price: 810527,
  //   monthlyPrice: "57894 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 213,
  //   label: "Chegirma",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product159.jpg",
  // },
  // {
  //   id: 160,
  //   title: "Hermes uslubidagi kamar",
  //   price: 466646,
  //   monthlyPrice: "33331 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 719,
  //   label: "Chegirma",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product160.jpg",
  // },
  // {
  //   id: 161,
  //   title: "Hermes uslubidagi kamar",
  //   price: 565966,
  //   monthlyPrice: "40426 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 93,
  //   label: "Katta savdo",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product161.jpg",
  // },
  // {
  //   id: 162,
  //   title: "Hermes uslubidagi kamar",
  //   price: 851245,
  //   monthlyPrice: "60803 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 417,
  //   label: "Super narx",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product162.jpg",
  // },
  // {
  //   id: 163,
  //   title: "Hermes uslubidagi kamar",
  //   price: 386553,
  //   monthlyPrice: "27610 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 111,
  //   label: "",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product163.jpg",
  // },
  // {
  //   id: 164,
  //   title: "Hermes uslubidagi kamar",
  //   price: 936521,
  //   monthlyPrice: "66894 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 307,
  //   label: "Yangi",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product164.jpg",
  // },
  // {
  //   id: 165,
  //   title: "Hermes uslubidagi kamar",
  //   price: 416166,
  //   monthlyPrice: "29726 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 867,
  //   label: "",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product165.jpg",
  // },
  // {
  //   id: 166,
  //   title: "Hermes uslubidagi kamar",
  //   price: 494866,
  //   monthlyPrice: "35347 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 832,
  //   label: "",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product166.jpg",
  // },
  // {
  //   id: 167,
  //   title: "Hermes uslubidagi kamar",
  //   price: 511225,
  //   monthlyPrice: "36516 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 931,
  //   label: "",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product167.jpg",
  // },
  // {
  //   id: 168,
  //   title: "Hermes uslubidagi kamar",
  //   price: 163647,
  //   monthlyPrice: "11689 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 986,
  //   label: "Super narx",
  //   category: "Kamarlar",
  //   image: "https://example.com/images/product168.jpg",
  // },
  // {
  //   id: 169,
  //   title: "iPhone 14 Pro",
  //   price: 141657,
  //   monthlyPrice: "10118 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 828,
  //   label: "Yangi",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product169.jpg",
  // },
  // {
  //   id: 170,
  //   title: "iPhone 14 Pro",
  //   price: 674493,
  //   monthlyPrice: "48178 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 542,
  //   label: "Chegirma",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product170.jpg",
  // },
  // {
  //   id: 171,
  //   title: "iPhone 14 Pro",
  //   price: 783160,
  //   monthlyPrice: "55940 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 533,
  //   label: "Super narx",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product171.jpg",
  // },
  // {
  //   id: 172,
  //   title: "iPhone 14 Pro",
  //   price: 264797,
  //   monthlyPrice: "18914 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 894,
  //   label: "Katta savdo",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product172.jpg",
  // },
  // {
  //   id: 173,
  //   title: "iPhone 14 Pro",
  //   price: 519927,
  //   monthlyPrice: "37137 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 548,
  //   label: "",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product173.jpg",
  // },
  // {
  //   id: 174,
  //   title: "iPhone 14 Pro",
  //   price: 991193,
  //   monthlyPrice: "70799 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 243,
  //   label: "Yangi",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product174.jpg",
  // },
  // {
  //   id: 175,
  //   title: "iPhone 14 Pro",
  //   price: 87904,
  //   monthlyPrice: "6278 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 376,
  //   label: "Yangi",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product175.jpg",
  // },
  // {
  //   id: 176,
  //   title: "iPhone 14 Pro",
  //   price: 388998,
  //   monthlyPrice: "27785 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 941,
  //   label: "",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product176.jpg",
  // },
  // {
  //   id: 177,
  //   title: "iPhone 14 Pro",
  //   price: 123619,
  //   monthlyPrice: "8829 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 286,
  //   label: "",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product177.jpg",
  // },
  // {
  //   id: 178,
  //   title: "iPhone 14 Pro",
  //   price: 333720,
  //   monthlyPrice: "23837 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 807,
  //   label: "",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product178.jpg",
  // },
  // {
  //   id: 179,
  //   title: "iPhone 14 Pro",
  //   price: 927174,
  //   monthlyPrice: "66226 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 232,
  //   label: "",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product179.jpg",
  // },
  // {
  //   id: 180,
  //   title: "iPhone 14 Pro",
  //   price: 842881,
  //   monthlyPrice: "60205 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 109,
  //   label: "",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product180.jpg",
  // },
  // {
  //   id: 181,
  //   title: "Samsung Galaxy S22",
  //   price: 962488,
  //   monthlyPrice: "68749 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 795,
  //   label: "Chegirma",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product181.jpg",
  // },
  // {
  //   id: 182,
  //   title: "Samsung Galaxy S22",
  //   price: 258529,
  //   monthlyPrice: "18466 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 195,
  //   label: "Super narx",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product182.jpg",
  // },
  // {
  //   id: 183,
  //   title: "Samsung Galaxy S22",
  //   price: 514442,
  //   monthlyPrice: "36745 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 836,
  //   label: "Yangi",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product183.jpg",
  // },
  // {
  //   id: 184,
  //   title: "Samsung Galaxy S22",
  //   price: 146628,
  //   monthlyPrice: "10473 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 387,
  //   label: "Yangi",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product184.jpg",
  // },
  // {
  //   id: 185,
  //   title: "Samsung Galaxy S22",
  //   price: 441974,
  //   monthlyPrice: "31569 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 841,
  //   label: "",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product185.jpg",
  // },
  // {
  //   id: 186,
  //   title: "Samsung Galaxy S22",
  //   price: 649282,
  //   monthlyPrice: "46377 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 889,
  //   label: "Yangi",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product186.jpg",
  // },
  // {
  //   id: 187,
  //   title: "Samsung Galaxy S22",
  //   price: 875580,
  //   monthlyPrice: "62541 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 812,
  //   label: "Katta savdo",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product187.jpg",
  // },
  // {
  //   id: 188,
  //   title: "Samsung Galaxy S22",
  //   price: 101112,
  //   monthlyPrice: "7222 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 552,
  //   label: "Super narx",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product188.jpg",
  // },
  // {
  //   id: 189,
  //   title: "Samsung Galaxy S22",
  //   price: 657378,
  //   monthlyPrice: "46955 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 544,
  //   label: "Yangi",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product189.jpg",
  // },
  // {
  //   id: 190,
  //   title: "Samsung Galaxy S22",
  //   price: 561614,
  //   monthlyPrice: "40115 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 53,
  //   label: "Super narx",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product190.jpg",
  // },
  // {
  //   id: 191,
  //   title: "Samsung Galaxy S22",
  //   price: 480037,
  //   monthlyPrice: "34288 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 865,
  //   label: "Yangi",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product191.jpg",
  // },
  // {
  //   id: 192,
  //   title: "Samsung Galaxy S22",
  //   price: 130669,
  //   monthlyPrice: "9333 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 754,
  //   label: "Super narx",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product192.jpg",
  // },
  // {
  //   id: 193,
  //   title: "Xiaomi Redmi Note 12",
  //   price: 91852,
  //   monthlyPrice: "6560 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 431,
  //   label: "Chegirma",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product193.jpg",
  // },
  // {
  //   id: 194,
  //   title: "Xiaomi Redmi Note 12",
  //   price: 355170,
  //   monthlyPrice: "25369 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 462,
  //   label: "",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product194.jpg",
  // },
  // {
  //   id: 195,
  //   title: "Xiaomi Redmi Note 12",
  //   price: 354604,
  //   monthlyPrice: "25328 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 217,
  //   label: "Chegirma",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product195.jpg",
  // },
  // {
  //   id: 196,
  //   title: "Xiaomi Redmi Note 12",
  //   price: 770920,
  //   monthlyPrice: "55065 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 250,
  //   label: "",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product196.jpg",
  // },
  // {
  //   id: 197,
  //   title: "Xiaomi Redmi Note 12",
  //   price: 829840,
  //   monthlyPrice: "59274 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 401,
  //   label: "Yangi",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product197.jpg",
  // },
  // {
  //   id: 198,
  //   title: "Xiaomi Redmi Note 12",
  //   price: 266789,
  //   monthlyPrice: "19056 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 794,
  //   label: "Yangi",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product198.jpg",
  // },
  // {
  //   id: 199,
  //   title: "Xiaomi Redmi Note 12",
  //   price: 569838,
  //   monthlyPrice: "40702 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 416,
  //   label: "Chegirma",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product199.jpg",
  // },
  // {
  //   id: 200,
  //   title: "Xiaomi Redmi Note 12",
  //   price: 434343,
  //   monthlyPrice: "31024 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 230,
  //   label: "",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product200.jpg",
  // },
  // {
  //   id: 201,
  //   title: "Xiaomi Redmi Note 12",
  //   price: 905615,
  //   monthlyPrice: "64686 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 451,
  //   label: "",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product201.jpg",
  // },
  // {
  //   id: 202,
  //   title: "Xiaomi Redmi Note 12",
  //   price: 983463,
  //   monthlyPrice: "70247 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 257,
  //   label: "",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product202.jpg",
  // },
  // {
  //   id: 203,
  //   title: "Xiaomi Redmi Note 12",
  //   price: 141217,
  //   monthlyPrice: "10086 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 135,
  //   label: "Super narx",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product203.jpg",
  // },
  // {
  //   id: 204,
  //   title: "Xiaomi Redmi Note 12",
  //   price: 377119,
  //   monthlyPrice: "26937 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 946,
  //   label: "Chegirma",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product204.jpg",
  // },
  // {
  //   id: 205,
  //   title: "Realme C55",
  //   price: 356106,
  //   monthlyPrice: "25436 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 573,
  //   label: "Yangi",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product205.jpg",
  // },
  // {
  //   id: 206,
  //   title: "Realme C55",
  //   price: 203179,
  //   monthlyPrice: "14512 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 752,
  //   label: "Super narx",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product206.jpg",
  // },
  // {
  //   id: 207,
  //   title: "Realme C55",
  //   price: 570682,
  //   monthlyPrice: "40763 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 630,
  //   label: "Yangi",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product207.jpg",
  // },
  // {
  //   id: 208,
  //   title: "Realme C55",
  //   price: 608376,
  //   monthlyPrice: "43455 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 59,
  //   label: "Super narx",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product208.jpg",
  // },
  // {
  //   id: 209,
  //   title: "Realme C55",
  //   price: 344406,
  //   monthlyPrice: "24600 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 953,
  //   label: "Katta savdo",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product209.jpg",
  // },
  // {
  //   id: 210,
  //   title: "Realme C55",
  //   price: 539281,
  //   monthlyPrice: "38520 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 488,
  //   label: "Yangi",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product210.jpg",
  // },
  // {
  //   id: 211,
  //   title: "Realme C55",
  //   price: 405393,
  //   monthlyPrice: "28956 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 470,
  //   label: "Super narx",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product211.jpg",
  // },
  // {
  //   id: 212,
  //   title: "Realme C55",
  //   price: 417948,
  //   monthlyPrice: "29853 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 531,
  //   label: "Chegirma",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product212.jpg",
  // },
  // {
  //   id: 213,
  //   title: "Realme C55",
  //   price: 229120,
  //   monthlyPrice: "16365 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 584,
  //   label: "Katta savdo",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product213.jpg",
  // },
  // {
  //   id: 214,
  //   title: "Realme C55",
  //   price: 876057,
  //   monthlyPrice: "62575 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 105,
  //   label: "",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product214.jpg",
  // },
  // {
  //   id: 215,
  //   title: "Realme C55",
  //   price: 250307,
  //   monthlyPrice: "17879 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 527,
  //   label: "Yangi",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product215.jpg",
  // },
  // {
  //   id: 216,
  //   title: "Realme C55",
  //   price: 937725,
  //   monthlyPrice: "66980 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 73,
  //   label: "Yangi",
  //   category: "Telefonlar",
  //   image: "https://example.com/images/product216.jpg",
  // },
  // {
  //   id: 217,
  //   title: "ASUS VivoBook",
  //   price: 733809,
  //   monthlyPrice: "52414 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 801,
  //   label: "Chegirma",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product217.jpg",
  // },
  // {
  //   id: 218,
  //   title: "ASUS VivoBook",
  //   price: 503115,
  //   monthlyPrice: "35936 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 556,
  //   label: "Chegirma",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product218.jpg",
  // },
  // {
  //   id: 219,
  //   title: "ASUS VivoBook",
  //   price: 603523,
  //   monthlyPrice: "43108 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 488,
  //   label: "Katta savdo",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product219.jpg",
  // },
  // {
  //   id: 220,
  //   title: "ASUS VivoBook",
  //   price: 538195,
  //   monthlyPrice: "38442 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 402,
  //   label: "Katta savdo",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product220.jpg",
  // },
  // {
  //   id: 221,
  //   title: "ASUS VivoBook",
  //   price: 135166,
  //   monthlyPrice: "9654 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 286,
  //   label: "Chegirma",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product221.jpg",
  // },
  // {
  //   id: 222,
  //   title: "ASUS VivoBook",
  //   price: 498064,
  //   monthlyPrice: "35576 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 936,
  //   label: "",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product222.jpg",
  // },
  // {
  //   id: 223,
  //   title: "ASUS VivoBook",
  //   price: 315062,
  //   monthlyPrice: "22504 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 542,
  //   label: "Katta savdo",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product223.jpg",
  // },
  // {
  //   id: 224,
  //   title: "ASUS VivoBook",
  //   price: 381394,
  //   monthlyPrice: "27242 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 561,
  //   label: "Chegirma",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product224.jpg",
  // },
  // {
  //   id: 225,
  //   title: "ASUS VivoBook",
  //   price: 370425,
  //   monthlyPrice: "26458 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 239,
  //   label: "Chegirma",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product225.jpg",
  // },
  // {
  //   id: 226,
  //   title: "ASUS VivoBook",
  //   price: 683501,
  //   monthlyPrice: "48821 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 955,
  //   label: "Katta savdo",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product226.jpg",
  // },
  // {
  //   id: 227,
  //   title: "ASUS VivoBook",
  //   price: 432302,
  //   monthlyPrice: "30878 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 549,
  //   label: "Katta savdo",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product227.jpg",
  // },
  // {
  //   id: 228,
  //   title: "ASUS VivoBook",
  //   price: 546818,
  //   monthlyPrice: "39058 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 788,
  //   label: "Katta savdo",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product228.jpg",
  // },
  // {
  //   id: 229,
  //   title: "Lenovo IdeaPad",
  //   price: 978053,
  //   monthlyPrice: "69860 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 436,
  //   label: "",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product229.jpg",
  // },
  // {
  //   id: 230,
  //   title: "Lenovo IdeaPad",
  //   price: 579260,
  //   monthlyPrice: "41375 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 947,
  //   label: "Super narx",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product230.jpg",
  // },
  // {
  //   id: 231,
  //   title: "Lenovo IdeaPad",
  //   price: 543167,
  //   monthlyPrice: "38797 so'm/oyiga",
  //   rating: 4.8,
  //   reviewCount: 622,
  //   label: "",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product231.jpg",
  // },
  // {
  //   id: 232,
  //   title: "Lenovo IdeaPad",
  //   price: 86604,
  //   monthlyPrice: "6186 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 851,
  //   label: "",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product232.jpg",
  // },
  // {
  //   id: 233,
  //   title: "Lenovo IdeaPad",
  //   price: 796382,
  //   monthlyPrice: "56884 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 516,
  //   label: "Katta savdo",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product233.jpg",
  // },
  // {
  //   id: 234,
  //   title: "Lenovo IdeaPad",
  //   price: 130875,
  //   monthlyPrice: "9348 so'm/oyiga",
  //   rating: 4.6,
  //   reviewCount: 80,
  //   label: "Yangi",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product234.jpg",
  // },
  // {
  //   id: 235,
  //   title: "Lenovo IdeaPad",
  //   price: 966563,
  //   monthlyPrice: "69040 so'm/oyiga",
  //   rating: 4.5,
  //   reviewCount: 227,
  //   label: "",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product235.jpg",
  // },
  // {
  //   id: 236,
  //   title: "Lenovo IdeaPad",
  //   price: 780802,
  //   monthlyPrice: "55771 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 682,
  //   label: "Super narx",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product236.jpg",
  // },
  // {
  //   id: 237,
  //   title: "Lenovo IdeaPad",
  //   price: 726200,
  //   monthlyPrice: "51871 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 988,
  //   label: "Katta savdo",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product237.jpg",
  // },
  // {
  //   id: 238,
  //   title: "Lenovo IdeaPad",
  //   price: 859296,
  //   monthlyPrice: "61378 so'm/oyiga",
  //   rating: 4.7,
  //   reviewCount: 81,
  //   label: "Chegirma",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product238.jpg",
  // },
  // {
  //   id: 239,
  //   title: "Lenovo IdeaPad",
  //   price: 123627,
  //   monthlyPrice: "8830 so'm/oyiga",
  //   rating: 5.0,
  //   reviewCount: 88,
  //   label: "",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product239.jpg",
  // },
  // {
  //   id: 240,
  //   title: "Lenovo IdeaPad",
  //   price: 916486,
  //   monthlyPrice: "65463 so'm/oyiga",
  //   rating: 4.9,
  //   reviewCount: 118,
  //   label: "Super narx",
  //   category: "Noutbuklar",
  //   image: "https://example.com/images/product240.jpg",
  // },
];

const data = {
  mahsulotKategoriya,
  sliderImages,
  fourtProduct,
  productCard,
};

export default data;
